### PR TITLE
Update to Minecraft 1.20.4 and update Russian translations

### PR DESCRIPTION
**Pull request by MushroomMif**
Some notes:
- Gradle was updated to 8.3 because Loom 1.4 requires it
- Version of the mod was bumped to 1.10.2
- Removed MixinExtras dependency because it is now embedded in the Fabric Loader
- Server Translations API was moved to `xyz.nucleoid` repository by it's developers

### CODE REVIEW

**Comment by MushroomMif** [comment]
And also it closes #56

**Comment by Steveplays28** [comment]
Hi! Thanks for this, MushroomMif, I'll merge it into a new branch and release it.
It'll take some time for me to merge this though since you based this on the main branch, instead of the newest branch, `1.20.2`.

**Comment by MushroomMif** [comment]
Oh, sorry for that 😅 
Hope it wouldn't be hard to do that

**Comment by Steveplays28** [comment]
All good.

**Comment by Steveplays28** [comment]
I added your Russian translation update and the 1.20.3/1.20.4 update, see above.
Thanks again!

**Pull request closed without merging**
