### PR TITLE
More Configurability

### PR DESCRIPTION
**Pull request by RickyTheRacc**
Adds two config options:

sendDawnMessage - specifies whether to send the dawn message, makes sense since a "sendSleepingMessage" option is also provided and makes disabling the message more obvious

showTimeUntilDawn - specifies whether the time until dawn should be appended to the sleeping message, made true by default. Allows for greater vanilla parity 

Also changed the construction of the sleeping message to use String.format() which would maybe have a tiiiiiiny improvement for memory use lol

### CODE REVIEW

**Comment by RickyTheRacc** [comment]
For sure! Was just perusing mods for a server I'm making and thought of a few features ^^

I could work on making a TPS tracker of some sort like I saw in #7 but I can't guarantee when or if that would get done, probably after I get the server up and running

**Comment by Steveplays28** [comment]
That would be neat! Maybe we could depend on Carpet Core, because I believe it has TPS tracker functionality in its API.

**Comment by Steveplays28** [comment]
Could you rebase against main? Did some cleanup that I forgot to cherry pick from the 1.20 branch.

**Comment by RickyTheRacc** [comment]
Ope- Completely slipped my mind, let me take care of that ye

**Comment by RickyTheRacc** [comment]
I think this should do it? I have no idea how rebasing works but I selected my stuff, if this is not right I will just refork it 💀

**Comment by Steveplays28** [comment]
That seems to be fine! I'll merge and release it sometime soon.
Still need to look into your issue.

**Comment by Steveplays28** [comment]
Thanks! Will look into your issue sometime next week.

**Pull request merged**
