### PR TITLE
Daytime Sleeping & en_us.json Improvements

### LINKED ISSUE #21: Add option to allow sleeping during daytime

### PR DESCRIPTION
**Pull request by Superkat32**
This PR does 2 main things.
1. Adds (toggleable) day time sleeping! (Closes #21)
2. Some slight improvements to en_us.json for config tooltips on larger GUI sizes(e.g. GUI size 4)

Daytime Sleeping:
Sleeping through the day to dusk is now possible. It can be optionally toggled in the config, along with some other config options for the seconds until dusk message and the night time message. For the night time message, I decided to make it "The night begins." instead of "The moon rises", as I felt like the second option would have been too obvious. However, this is easily changeable in the config. Additionally, I also renamed the "WAKE_UP_TIME" int to be "SUNRISE_WAKE_UP", as a second `private static int` needed to be added.

The actual daytime sleeping works by using a FabricApi method, which also works with Quilt in my quick testing. It then checks if the config option is enabled or disabled, then decides what to do from there. If enabled, it allows the user to sleep in the bed(even during the day), otherwise, it returns the vanilla action.

en_us.json Improvements:
Firstly, lots of the longer tooltips have been reduced in length to be more easily readable on larger GUI sizes. I made this its own commit so it should be easy to reverse if you don't like it. Secondly, the config title has changed from "Realistic Sleep mod config" to "Realistic Sleep Config". This helps make it seem more in line with other config titles(e.g. Video Settings, Key Binds, Mouse Settings, Mod Menu Options, etc.)

Video:
A quick video showcase of the PR. Happy Modtoberfest!

https://github.com/Steveplays28/realisticsleep/assets/89557012/34483955-9c36-40cd-a810-27709e3a7fad

### CODE REVIEW

**Comment by Superkat32** [comment]
I forgot to mention this earlier, but I also added missing translation keys in en_us.json for some of the config options.

**Comment by Steveplays28** [comment]
Hi Superkat, this PR looks really good!
I'll merge it sometime this weekend and release the update.

Thanks a lot for the contribution, good luck with the rest of Modtoberfest (and beyond)!

**Comment by Superkat32** [comment]
Glad you like it! It was a lot of fun to put together. Modtoberfest has challenged me to do things I never would've thought of doing, and it's been really great.

If there's anything that needs changing, I can definitely change it.

**Comment by Steveplays28** [comment]
Thanks for the contribution Superkat! I'll try to get this released today.

**Comment by Superkat32** [comment]
No worries! Don't feel the need to rush a release out if you don't have the time. Thanks for merging!

**Pull request merged**
