### PR TITLE
1.21 port

### PR DESCRIPTION
**Pull request by wMarciano**

### CODE REVIEW

**Comment by Steveplays28** [comment]
Hi wMarciano, thank you for the PR!
I'll merge this after porting all 1.20.x versions to (Neo)Forge.

Also FYI, I'm going to rename this repository to `stevesrealisticsleep`.

**Comment by Legendmanj** [comment]
approve!! i would like to have it on 1.21 (;

**Comment by wMarciano** [comment]
> approve!! i would like to have it on 1.21 (;

In the mean time, it's available from my fork's actions:
https://github.com/wMarciano/realisticsleep/actions/runs/9620310592

Or here:
[realisticsleep-1.10.3+mc1.21.zip](https://github.com/user-attachments/files/16339232/realisticsleep-1.10.3%2Bmc1.21.zip)

**Comment by Legendmanj** [comment]
> > approve!! i would like to have it on 1.21 (;
> 
> In the mean time, it's available from my fork's actions: https://github.com/wMarciano/realisticsleep/actions/runs/9620310592
> 
> Or here: [realisticsleep-1.10.3+mc1.21.zip](https://github.com/user-attachments/files/16339232/realisticsleep-1.10.3%2Bmc1.21.zip)

crazy thankyou (;

**Comment by Steveplays28** [comment]
Released in [`v1.11.0`](https://github.com/steves-underwater-paradise/stevesrealisticsleep/releases/latest). Thanks again @wMarciano!
I've added you as a co-author in the version number/changelog commit.

**Pull request closed without merging**
